services:
  retrovault:
    build:
      context: https://github.com/theretrovault/retrovault.git#prod
      dockerfile: retrovault/Dockerfile
    container_name: retrovault
    restart: unless-stopped
    ports:
      - "3099:3000"
    volumes:
      - retrovault-data:/app/data
      - retrovault-logs:/app/logs
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: file:/app/data/retrovault.db

volumes:
  retrovault-data:
  retrovault-logs: