version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: will-obico_web_1
      APP_PORT: 3334
      PROXY_AUTH_ADD: false

  web:
    image: ghcr.io/thespaghettidetective/web:latest
    restart: unless-stopped
    depends_on:
      - redis
      - ml_api
    environment:
      DEBUG: "False"
      SITE_USES_HTTPS: "False"
      SITE_IS_PUBLIC: "False"
      ACCOUNT_ALLOW_SIGN_UP: "True"
      REDIS_URL: redis://redis:6379
      ML_API_HOST: http://ml_api:3333
      DATABASE_URL: sqlite:////data/db.sqlite3
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY:-change-this-secret-key}"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/media:/app/static_build/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 3334 config.routing:application"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3334/hc/ || exit 1"]
      start_period: 90s
      interval: 60s
      timeout: 20s
      retries: 5

  tasks:
    image: ghcr.io/thespaghettidetective/web:latest
    restart: unless-stopped
    depends_on:
      - redis
      - ml_api
    environment:
      DEBUG: "False"
      REDIS_URL: redis://redis:6379
      ML_API_HOST: http://ml_api:3333
      DATABASE_URL: sqlite:////data/db.sqlite3
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY:-change-this-secret-key}"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/media:/app/static_build/media
    command: >
      sh -c "celery -A config worker --beat -l info -c 2 -Q realtime,celery"

  ml_api:
    image: ghcr.io/thespaghettidetective/ml_api:latest
    restart: unless-stopped
    environment:
      DEBUG: "False"
    command: >
      gunicorn --bind 0.0.0.0:3333 --workers 1 wsgi
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3333/hc/ || exit 1"]
      start_period: 90s
      interval: 30s
      timeout: 15s
      retries: 5

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      start_period: 15s
      interval: 15s
      timeout: 10s
      retries: 20