version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: will-obico_web_1
      APP_PORT: 3334
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/williamcarlos2/will-obico-web:latest
    restart: unless-stopped
    environment:
      DEBUG: "False"
      SITE_USES_HTTPS: "False"
      SITE_IS_PUBLIC: "False"
      ACCOUNT_ALLOW_SIGN_UP: "True"
      WEBPACK_LOADER_ENABLED: "False"

      REDIS_URL: redis://redis:6379
      DATABASE_URL: sqlite:////data/db.sqlite3
      ML_API_HOST: http://ml_api:3333
      INTERNAL_MEDIA_HOST: http://web:3334

      OCTOPRINT_TUNNEL_PORT_RANGE: "0-0"
      DEFAULT_FROM_EMAIL: changeme@example.com

      DJANGO_SECRET_KEY: "will-obico-umbrel-local-key-change-me"

    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/media:/app/static_build/media

    depends_on:
      - redis
      - ml_api

    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic -v 2 --noinput &&
             daphne -b 0.0.0.0 -p 3334 config.routing:application"

  tasks:
    image: ghcr.io/williamcarlos2/will-obico-web:latest
    restart: unless-stopped

    environment:
      DEBUG: "False"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: sqlite:////data/db.sqlite3
      ML_API_HOST: http://ml_api:3333
      INTERNAL_MEDIA_HOST: http://web:3334
      DJANGO_SECRET_KEY: "will-obico-umbrel-local-key-change-me"

    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/media:/app/static_build/media

    depends_on:
      - redis
      - ml_api

    command: >
      celery -A config worker --beat -l info -c 2 -Q realtime,celery

  ml_api:
    image: ghcr.io/thespaghettidetective/ml_api:latest
    restart: unless-stopped
    environment:
      DEBUG: "True"
      FLASK_APP: server.py

    command: >
      bash -c "gunicorn --bind 0.0.0.0:3333 --workers 1 wsgi"

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped