version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: will-layernexus_web_1
      APP_PORT: 8000

  web:
    build:
      context: https://github.com/peterus/LayerNexus.git#main
      target: release
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/media:/app/media
      - ${APP_DATA_DIR}/data/db:/app/data
    environment:
      DJANGO_SECRET_KEY: "${APP_SEED}"
      DEBUG: "0"
      ALLOWED_HOSTS: "*"
      CSRF_TRUSTED_ORIGINS: "http://${DEVICE_DOMAIN_NAME},https://${DEVICE_DOMAIN_NAME}"
      ORCASLICER_API_URL: "http://will-layernexus_orcaslicer_1:3000"
      SPOOLMAN_URL: "http://host.docker.internal:7912"
      ALLOW_REGISTRATION: "true"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - orcaslicer

  worker:
    build:
      context: https://github.com/peterus/LayerNexus.git#main
      target: release
    entrypoint: []
    command: ["python", "manage.py", "moonraker_worker"]
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/media:/app/media
      - ${APP_DATA_DIR}/data/db:/app/data
    environment:
      DJANGO_SECRET_KEY: "${APP_SEED}"
      DEBUG: "0"
      LOG_LEVEL: "INFO"
      WORKER_RELOAD_INTERVAL: "10"
      ORCASLICER_API_URL: "http://will-layernexus_orcaslicer_1:3000"
      SPOOLMAN_URL: "http://host.docker.internal:7912"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - web

  orcaslicer:
    image: ghcr.io/afkfelix/orca-slicer-api:latest-orca2.3.1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/orcaslicer:/app/data
